In [381]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv


In [382]:
df = pd.read_csv("/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv")

In [383]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [384]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [385]:
df=df.sample(10000)

In [386]:
df

review sentiment
7685   Well, the first thing I saw after looking at t...  negative
36106  How to Lose Friends & Alienate People is in al...  positive
10654  A look at three geishas who are way past their...  positive
15084  My title ought to be enough.<br /><br />It baf...  negative
1602   It's the worst movie I've ever seen. The actio...  negative
...                                                  ...       ...
17843  The antiwar musical "Hair" is my number one cu...  positive
34218  His choice of films, the basic 'conceit' of th...  positive
301    Serum is about a crazy doctor that finds a ser...  negative
44757  No,no,no. That is my advice to you if you are ...  negative
34502  This movie is one of the worst movies I have e...  negative

[10000 rows x 2 columns]

In [387]:
df.shape

(10000, 2)

In [388]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 7685 to 34502
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB


In [389]:
df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

In [390]:
df.head()

review  sentiment
7685   Well, the first thing I saw after looking at t...          0
36106  How to Lose Friends & Alienate People is in al...          1
10654  A look at three geishas who are way past their...          1
15084  My title ought to be enough.<br /><br />It baf...          0
1602   It's the worst movie I've ever seen. The actio...          0

In [391]:
import re
clean = re.compile('<.*?>')
re.sub(clean,'',df.iloc[1].review)

'How to Lose Friends & Alienate People is in all honesty one of the best comedies I\'ve seen this year along with Pineapple Express and Step Brothers. Its not one of those "gross out" comedies that heavily relies on fart jokes and toilet humor but instead moves at an affable pace and you will be easily attached to the unfolding narrative. Simon Pegg nails it in the coffin with his hilarious portrayal of a fish-out-of-water character and is quickly detaching himself from the tripod he once belonged to back in England (the other two would be Nick Frost and Edgar Wright). Getting yourself in the top of the Hollywood food chain is a hard thing to do as we can clearly see with Pegg, his first jab at the lead role was David Schwimmer\'s comedy Run Fatboy Run but it received lukewarm reviews from critics and audiences alike. His second try is this movie, got fairly positive reviews from the majority but was a flop in the box office. I, for one still haven\'t lost faith in him and I\'ll still 

In [392]:
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean,'',text)

In [393]:
df['review'] = df['review'].apply(clean_html)

In [394]:
df

review  sentiment
7685   Well, the first thing I saw after looking at t...          0
36106  How to Lose Friends & Alienate People is in al...          1
10654  A look at three geishas who are way past their...          1
15084  My title ought to be enough.It baffles me that...          0
1602   It's the worst movie I've ever seen. The actio...          0
...                                                  ...        ...
17843  The antiwar musical "Hair" is my number one cu...          1
34218  His choice of films, the basic 'conceit' of th...          1
301    Serum is about a crazy doctor that finds a ser...          0
44757  No,no,no. That is my advice to you if you are ...          0
34502  This movie is one of the worst movies I have e...          0

[10000 rows x 2 columns]

In [395]:
def convert_lower(text):
    return text.lower()


In [396]:
df['review'] = df['review'].apply(convert_lower)

In [397]:
df

review  sentiment
7685   well, the first thing i saw after looking at t...          0
36106  how to lose friends & alienate people is in al...          1
10654  a look at three geishas who are way past their...          1
15084  my title ought to be enough.it baffles me that...          0
1602   it's the worst movie i've ever seen. the actio...          0
...                                                  ...        ...
17843  the antiwar musical "hair" is my number one cu...          1
34218  his choice of films, the basic 'conceit' of th...          1
301    serum is about a crazy doctor that finds a ser...          0
44757  no,no,no. that is my advice to you if you are ...          0
34502  this movie is one of the worst movies i have e...          0

[10000 rows x 2 columns]

In [398]:
def remove_special(text):
    x=''
    
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x+' '
    return x

In [399]:
df['review'] = df['review'].apply(remove_special)

In [400]:
df

review  sentiment
7685   well  the first thing i saw after looking at t...          0
36106  how to lose friends   alienate people is in al...          1
10654  a look at three geishas who are way past their...          1
15084  my title ought to be enough it baffles me that...          0
1602   it s the worst movie i ve ever seen  the actio...          0
...                                                  ...        ...
17843  the antiwar musical  hair  is my number one cu...          1
34218  his choice of films  the basic  conceit  of th...          1
301    serum is about a crazy doctor that finds a ser...          0
44757  no no no  that is my advice to you if you are ...          0
34502  this movie is one of the worst movies i have e...          0

[10000 rows x 2 columns]

In [401]:
#Remove stopwards
import nltk

In [402]:
from nltk.corpus import stopwords


In [403]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [404]:
def remove_stopwords(text):
    x=[]
    for i in text.split():
        
        if i not in stopwords.words('english'):
            x.append(i)
    y=x[:]
    x.clear()
    return y

In [405]:
df['review'] = df['review'].apply(remove_stopwords)

In [406]:
df

review  sentiment
7685   [well, first, thing, saw, looking, dvd, box, b...          0
36106  [lose, friends, alienate, people, honesty, one...          1
10654  [look, three, geishas, way, past, prime, look,...          1
15084  [title, ought, enough, baffles, culture, rich,...          0
1602   [worst, movie, ever, seen, action, unclear, wo...          0
...                                                  ...        ...
17843  [antiwar, musical, hair, number, one, cult, mo...          1
34218  [choice, films, basic, conceit, production, pl...          1
301    [serum, crazy, doctor, finds, serum, supposed,...          0
44757  [advice, wanting, see, film, anthony, perkins,...          0
34502  [movie, one, worst, movies, ever, seen, cast, ...          0

[10000 rows x 2 columns]

In [407]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [408]:
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z

In [409]:
df['review'] = df['review'].apply(stem_words)

In [410]:
def join_back(list_input):
    return " ".join(list_input)

In [411]:
df['review'] = df['review'].apply(join_back)

In [412]:
df['review']

7685     well first thing saw look dvd box best screenp...
36106    lose friend alien peopl honesti one best comed...
10654    look three geisha way past prime look back pas...
15084    titl ought enough baffl cultur rich literari e...
1602     worst movi ever seen action unclear work camer...
                               ...                        
17843    antiwar music hair number one cult movi know m...
34218    choic film basic conceit product place set sim...
301      serum crazi doctor find serum suppos cure dise...
44757    advic want see film anthoni perkin one norman ...
34502    movi one worst movi ever seen cast fantast mov...
Name: review, Length: 10000, dtype: object

In [413]:
X=df.iloc[:,0:1].values

In [414]:
X.shape

(10000, 1)

In [415]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [416]:
X = cv.fit_transform(df['review']).toarray()

In [417]:
X.shape

(10000, 36079)

In [418]:
X[0]

array([0, 0, 0, ..., 0, 0, 0])

In [420]:
X[0].max()

4

In [421]:
X[0].mean()

0.0019956207211951553

In [423]:
y=df.iloc[:,-1].values

In [424]:
y.shape

(10000,)

In [429]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [430]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 36079)
(2000, 36079)
(8000,)
(2000,)


In [431]:
y_test

array([1, 1, 1, ..., 1, 0, 1])

In [432]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [434]:
clf1=GaussianNB()
clf2=MultinomialNB()
clf3=BernoulliNB()

In [435]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)

BernoulliNB()

In [436]:
y_pred1=clf1.predict(X_test)
y_pred1=clf2.predict(X_test)
y_pred1=clf3.predict(X_test)

In [437]:
y_pred1.shape

(2000,)

In [440]:
y_pred1

array([1, 1, 1, ..., 1, 0, 1])

In [441]:
y_test

array([1, 1, 1, ..., 1, 0, 1])

In [439]:
from sklearn.metrics import accuracy_score

In [442]:
print("Gaussian",accuracy_score(y_test,y_pred1))
print("Multinomial",accuracy_score(y_test,y_pred1))
print("Bernoulli",accuracy_score(y_test,y_pred1))

Gaussian 0.8275
Multinomial 0.8275
Bernoulli 0.8275
